name: New Feature
description: Template to create a new feature
title: "[DATE]: [FEATURE NAME]"
labels: ["enhancement","feature"]
assignees: ["bidwolf","Francis1408","luizleroy01","PedroRonzani18"]
body:
- type: dropdown
  id: feature
  attributes:
    label: What your feature is related?
    options:
      - Courses
      - Security
      - Backend
      - Devops/Deploy
      - UI/UX
      - Another
  validations:
    required: true

- type: markdown
  attributes:
    value: |
      "### Description "
      Describe your feature

- type: markdown
  attributes:
    value: |
      "### Tasks "
      Your tasks to be done
      - [ ] TASK-1
      - [ ] TASK-2
      - [ ] TASK-3

- type: markdown
  attributes:
    value: |
      "### Acceptance Criteria"
       List of conditions that your feature must meet to be considered complete:
       1. First Criteria
       2. Second Criteria
