name: New Feature
description: Template to create a new feature
title: "[New Feature]: "
labels: ["enhancement","feature"]
assignees: ["bidwolf","Francis1408","luizleroy01","PedroRonzani18"]
body:
- type: dropdown
  id: feature
  attributes:
    label: What your feature is related?
    options:
      - Courses
      - Backend
      - UI/UX
      - Another
  validations:
    required: true

- type: textarea
  id: descr
  attributes:
    label: Feature description
    description: "The feature Description"
    value: |
      1.
      2.
      3.
      ...
    render: markdown
  validations:
    required: true
