name: New Feature
description: Template to create a new feature
title: "[New Feature]: "
labels: ["enhancement","feature"]
assignees:
  - bidwolf
  - Francis1408
  - luizleroy01
  - PedroRonzani18
body:
- type: dropdown
  id: feature
  attributes:
    label: What your feature is related?
    options:
      - Courses
      - Backend
      - UI/UX
      - Another
  validations:
    required: true
- type: markdown
    attributes:
      value: '## Descrição da Feature\n\n[Descreva aqui a sua feature detalhadamente]'
- type: markdown
    attributes:
      value: '## Motivação\n\n[Explique por que essa feature é importante e como ela pode ajudar os usuários] '
- type: markdown
    attributes :
      value: '## Proposta\n\n[Descreva aqui como essa feature pode ser implementada e como ela funciona]'
- type: markdown
    attributes :
      value: '## Tarefas\n- [ ] Tarefa 1\n- [ ] Tarefa 2\n- [ ] Tarefa 3'
- milestone:
    - Home
 
