import Head from 'next/head'
import { Inter } from 'next/font/google'
import Footer from '@/components/Footer'
import { useContext } from 'react'
import { AuthContext } from '@/context/auth/AuthContext'
import { Button, Heading, Text } from '@codelife-ui/react'
// import NavBar from '@/components/NavBar' Componente com defeito visual: linha 23

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const { signIn } = useContext(AuthContext)
  return (
    <>
      <Head>
        <title>Codelife</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mb-20">
        {/* <NavBar /> Componente com defeito visual no sm breakpoint */}
        <Heading size={'xl'} css={{ textAlign: 'center' }}>
          Aprenda a desenvolver websites
        </Heading>
        <Text>
          Lorem ipsum dolor sit, amet consectetur adipisicing elit. A ex nisi
          aliquid adipisci, ratione nulla exercitationem porro! Perspiciatis
          quae voluptatem numquam quis officiis, nobis, quaerat perferendis hic,
          ad dolore deserunt.
        </Text>
        <Button
          onClick={() =>
            signIn({ email: 'teste@teste.com', password: '123456' })
          }
          className="bg-codelife-green-400 text-codelife-black-700 rounded-sm text-lg"
        >
          SIGN IN
        </Button>
      </main>
      <Footer />
    </>
  )
}
